### ISSUE TITLE
Script para llenar info de profesores y talleres

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#11]
En la base de datos, junto a su relación con cada Workshop Period

**Comment by ralamosm** [comment]
@tomgranuja necesitamos que los profes se vayan subiendo a mirar el /admin/ para que asi nos cuenten que hechan en falta o cosas asi

**Comment by tomgranuja** [comment]
Ok, todavía no colecto sus ruts, trataré de tenerlos para el viernes.

**Comment by ralamosm** [comment]
@tomgranuja recordar ponerle `member.is_staff = True` a los profesores aca.

**Comment by ralamosm** [comment]
@tomgranuja tambien recordar que ya tenemos Cycles, Schedules y Period creados en prod

**Comment by tomgranuja** [comment]
> @tomgranuja recordar ponerle `member.is_staff = True` a los profesores aca.

@ralamosm Hecho en [4a6dfc6](https://github.com/tomgranuja/CayumanDjango/commit/4a6dfc6082ea28fe9e1add1552bada4d1e33f4b7)
