### ISSUE TITLE
Manejar bien la UI publica cuando el usuario visitante no sea un estudiante

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#12]
Que debe ver alguien que no sea estudiante? el formulario no hace sentido porque alguien que no es estudiante no se inscribira a nada.

Creo que lo mas logico aca seria armar una pagina que liste los workshops disponibles durante el periodo actual, linkeando a cada una de sus paginas, ademas de linkearlos en el mismo formulario de inscripcion o vista de horario. Asi, si un profesor cae en cayuman, podra ver algo al menos y no una pagina vacia.

**Comment by ralamosm** [comment]
que opinas @tomgranuja ?

**Comment by tomgranuja** [comment]
Me parece genial! Igual había pensado algo así para ayudar en la difusión del proyecto educativo en la comunidad. Quizás hasta podría pedir que armemos una comisión "evidencias" que saque foto a algunos frutos de los talleres (construcciones, exposiciones, etc.) y que vayan quedando. Me parece bueno.

**Comment by ralamosm** [comment]
buena, se vienen cambios a los modelos entonces :D

**Comment by ralamosm** [comment]
Igual que en #3 se decidio solo hacer redirect de non-students a /admin
