### ISSUE TITLE
Vistas adicionales de admin.py

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#13]
Para ofrecer mas funcionalidades tales como:

- estudiantes por workshop_period

**Comment by ralamosm** [comment]
@tomgranuja la base de datos sera la fuente primera de informacion respecto a cada taller, entonces es necesario como minimo lo de poder listar los estudiantes de cada taller

**Comment by tomgranuja** [comment]
De acuerdo, trabajemos en esto.
