### ISSUE TITLE
Agregar soporte de mailgun

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#15]
Para correos transaccionales tales como forgot password u otros.

**Comment by tomgranuja** [comment]
Oh, no había pensado en eso. Como alternativa, crees que se pueda usar una cuenta de mail del hosting que ya tenemos, comunidadeducativacayuman.cl?
Porque podría generar una cuenta exclusiva para esas transacciones, y ese hosting nos da acceso IMAP y POP

**Comment by ralamosm** [comment]
@tomgranuja eso seria genial! Django necesita acceso SMTP para poder enviar emails, si el hosting de cayuman lo hace entonces estariamos listos por ese lado. Ahi me cuentas

**Comment by ralamosm** [comment]
@tomgranuja recordar crear una usuario de mail y enviarme las credenciales plz. Gracias!

**Comment by ralamosm** [comment]
Hecho y en prod
