### ISSUE TITLE
Habilitar paginas restantes de auth

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#3]
Falta:
* forgot password
* set new password
* account page (logged in) donde pueda cambiar password tambien

**Comment by tomgranuja** [comment]
De acuerdo. En account page podría cambiar el mail también?
Es que con Paula dejamos el mail de los apoderados anotados, para que solo los estudiantes mayores que ya usan sus correos los cambien por el de ellos si gustan.

**Comment by ralamosm** [comment]
dale, buena idea

**Comment by ralamosm** [comment]
Finalmente se definio no crear paginas de auth ni nada, y forzar a los non-students a irse a /admin.
