### ISSUE TITLE
Agregar django-maintenance

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#30]
Para poder tenerlo como alternativa para poner el sitio en "pausa" si es que ocurre algun error.

**Comment by tomgranuja** [comment]
Cómo funciona? congela la base de datos?

**Comment by ralamosm** [comment]
solo permite poner una pagina con un mensaje de "mantenimiento" si es que esta ocurriendo algun error en el sitio. Y se puede decidir si se le muestra a todos los usuarios, o solo loggeados pero no a los admines, etc.
