### ISSUE TITLE
Add field `enrollment_end` to `Period` model

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#35]
This is in order to avoid using `date_start` as an implicit date for ending enrollment.

**Comment by ralamosm** [comment]
@tomgranuja tengo esto listo. Agregue un campo `enrollment_end` al modelo `Period`. Si despues de lo que hables a la tarde lo ves bien puedo pasar esto a produccion.

**Comment by tomgranuja** [comment]
> @tomgranuja tengo esto listo. Agregue un campo `enrollment_end` al modelo `Period`. Si despues de lo que hables a la tarde lo ves bien puedo pasar esto a produccion.

De acuerdo, lo veo esta tarde y te confirmo

**Comment by ralamosm** [comment]
Confirmado esto? Para pasar a prod y continuar con las otras tareas
