### ISSUE TITLE
Admin WorkshopPeriod improvements

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#36]
The following improvements are considered for Admin WorkshopPeriod (/admin/cayuman/workshopperiod/):

- [x] Add filter by period to the right column
- [x] Add an action to export data to CSV
- [x] By default show only workshops related with "current" period. ("current period" will be defined in comments).
- [x] Add column "active" with a green or red icon for each row, so users can quickly understand if workshop is active or not.

**Comment by ralamosm** [comment]
"current period" shoud be defined as this:

- if current date falls within date_start and date_end of a period, then that's the current period.
- else, it's the last one as saved in DB.

**Comment by tomgranuja** [comment]
Ok, that way the view is cleaner.

**Comment by ralamosm** [comment]
@tomgranuja esto esta listo en prod. Ahora se puede exportar a CSV los registros de WorkshopPeriod. Debes seleccionar los registros a exportar y luego en el dropdown de "Accion" > Exportar seleccionados a CSV > Clic en "Ir" y se bajara el archivo CSV.

Ademas la vista de admin funcion bien con un segundo periodo andando y siempre muestra el periodo actual por defecto.

**Comment by tomgranuja** [comment]
> @tomgranuja esto esta listo en prod. Ahora se puede exportar a CSV los registros de WorkshopPeriod. Debes seleccionar los registros a exportar y luego en el dropdown de "Accion" > Exportar seleccionados a CSV > Clic en "Ir" y se bajara el archivo CSV.
> 
> Ademas la vista de admin funcion bien con un segundo periodo andando y siempre muestra el periodo actual por defecto.

Ohh, genial. Gracias Roberto, voy a probarlo. Esto iría a favor de cambiar a largo plazo la dependencia de mysql2sqlite.
