### ISSUE TITLE
Script to load new Workshops and WorkshopPeriods

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#38]
We need to think about loading the list of workshops for the new period soon, and be able to understand if loading them has any issues like understanding when a workshop coming from a spreadsheet needs to be created or is already created on DB.

**Comment by ralamosm** [comment]
Encontré un módulo Python que traduce el dump SQL de MySQL a SQLite.
Intentaré sacar los datos así para que puedas usarlos en local

**Comment by tomgranuja** [comment]
Ahh, perfecto. Gracias Roberto!

**Comment by ralamosm** [comment]
done
