### ISSUE TITLE
Añadir la quota de cada workshop en el formulario de home

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#6]
Para dar mas feedback al usuario

**Comment by ralamosm** [comment]
Listo en https://github.com/tomgranuja/CayumanDjango/tree/6-show-workshopperiod-quota

**Comment by ralamosm** [comment]
Se agrego soporte para mostrar numero de cupos restantes si el workshop_period tiene un max_students.

Ademas se agrego javascript para:
- Deshabilitar el radio button si cupos == 0
- reducir en 1 el numero de cupos mostrado si se chequea un radio button
- analogamente, aumentar en 1 los cupos mostrados si se deschequea un radio button

**Comment by tomgranuja** [comment]
Ohh, que buena!
