### ISSUE TITLE
Página de descripcion de cada workshop

### ISSUE THREAD

**Issue by ralamosm** [tomgranuja/CayumanDjango#9]
Usando el HTML provisto.

**Comment by tomgranuja** [comment]
Hay un pero, que es que no tendremos la información de las salas de cada taller con anticipación. Quizás en la vista de horario, de manera provisoria, se puede dejar algo así como "Bloque 1" - "Bloque 2" en el caso de un taller de 2 sesiones semanales.

**Comment by ralamosm** [comment]
@tomgranuja no hay problema

**Comment by ralamosm** [comment]
@tomgranuja puse un ticket en lugar de Bloque 1 o 2 porque esto ultimo resulta demasiado evidente. 

Pero bueno despues podemos mejorarlo.

Esto está hecho en rama https://github.com/tomgranuja/CayumanDjango/tree/6-show-workshopperiod-quota. Pasaré a main y prod de inmediato.
